Algoritmo "Atividade1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Escreva um algoritmo para ler um valor
//               e escreva seu antecessor
// Autor(a)    : Maria Vitória Jesus do Nascimento
// Data atual  : 23/10/2024
Var
num, antecessor: inteiro

Inicio
escreva("Digite um número: ")
   leia(num)
   antecessor := num - 1
   escreva("O antecessor de ", num, " é ", antecessor)

Fimalgoritmo