Algoritmo "ativ4.30-10"
// Autor(a)    : Maria Vitória Jesus do Nascimento
// Data atual  : 30/10/2024
Var
 num1, num2, num3, num4, soma: real

Inicio
 escreval("Digite o primeiro número: ")
  leia(num1)
  escreval("Digite o segundo número: ")
  leia(num2)
  escreval("Digite o terceiro número: ")
  leia(num3)
  escreval("Digite o quarto número: ")
  leia(num4)

  soma := num1 + num2 + num3 + num4

  escreval("A soma dos 4 números é: ", soma)

Fimalgoritmo